Update gridline_annotators and feature_annotators usage within code.
NRLMMD-GEOIPS/geoips pull request #215
Opened 2023-05-01 20:10 UTC by mindyls

Please do not merge these pull requests

# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#NNN

# Testing Instructions

# Summary

# Output

2023-05-02 15:18 UTC, mindyls commented
This gives 0 return now.  Let's hold off on merging until everything is working (including other repos), we can continue branching off the functional updates, and keep the new branches up to date as we go.

Package: geoips_full
Total run time: 670 seconds
Number data types run: 24
Number data types failed: 0

2023-05-05 17:27 UTC, jsolbrig requested changes
This has been working for a while with no issues. Approved, but waiting for approval on all other related PRs. Resolve this comment when ready to merge.

2023-05-05 17:29 UTC, jsolbrig approved these changes
This is approved conditional on all other related PRs being approved.

2023-05-05 17:30 UTC, jsolbrig commented on docs/source/releases/v1_10_0a12.rst
Please resolve this comment when all related PRs are ready to merge.

2023-05-10 04:29 UTC, merged