Update Coverage Checkers to use either varname or product name
NRLMMD-GEOIPS/geoips pull request #243
Opened 2023-07-11 20:33 UTC by evrose54

# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#227

# Summary
These changes reflect the need to simplify naming conventions in the coverage_checkers modules. Per issue #227, these names were ambiguous and tangled, and the new changes create an easier, simpler way to name the outputted coverage checkers. The files changed are listed below.

  - geoips/plugins/modules/coverage_checkers/center_radius_rgba.py
  - geoips/plugins/modules/coverage_checkers/center_radius.py
  - geoips/plugins/modules/coverage_checkers/masked_arrays.py
  - geoips/plugins/modules/coverage_checkers/numpy_arrays_nan.py
  - geoips/plugins/modules/coverage_checkers/rgba.py
  - geoips/plugins/modules/coverage_checkers/windbarbs.py

2023-08-14 19:54 UTC, mindyls commented
@evrose54 Have you run $GEOIPS_PACKAGES_DIR/geoips/tests/integration_tests/full_test.sh with these changes? If so, can you paste the output here?  If additional PRs are required (ie, on data_fusion repo, etc), please include links to all other required PRs as well.

There should be a complete 0 return for all updates - and if these changes aren't tested, please add a test to ensure these updates are fully tested prior to finalizing PR.

2023-08-14 19:56 UTC, mindyls requested changes
Please run $GEOIPS/tests/integration_tests/full_test.sh, and include the full 0 return in the PR contents.  Also link to any other PRs that were required to get the 0 return.

2023-08-15 21:21 UTC, jsolbrig approved these changes

2023-08-15 21:23 UTC, mindyls approved these changes
I'm good merging this, and I'll test after merge.

2023-08-15 21:25 UTC, merged

2023-08-16 21:37 UTC, mindyls commented on geoips/plugins/modules/coverage_checkers/center_radius.py
> +            name,
Looking at this closer, I don't think this is what we want - it is using the name of the coverage checker plugin if the variable name does not exist in the xarray object.  I don't think that makes sense.  I will think about how this works, and expect an updated implementation when 1.11.1 is released.