260 update sector schema to allow simplified specification
NRLMMD-GEOIPS/geoips pull request #279
Opened 2023-08-22 22:01 UTC by jsolbrig

# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#NNN

# Testing Instructions

# Summary

# Output

2023-08-27 15:29 UTC, jsolbrig commented
For now, in this PR, I will not implement `center` and `corners` families. Instead, I have just simplified the `area_definition` based sectors by making them use the `center` property rather than `area_extent`. This still results in a fully defined `AreaDefinition` without needing to compute `area_extent`.

For `center` and `corners`, please see issues #284 and #301.

2023-08-27 16:23 UTC, jsolbrig commented on geoips/interfaces/base.py
> +        # See issue #303
I created issue #303 to deal with this, but would like to leave this as an example for use in #303.

2023-08-27 16:24 UTC, jsolbrig commented on geoips/interfaces/yaml_based/sectors.py
> +# Will work on this again after the 2023 workshop
I added #301 to work on this. I'd like to leave these here as examples for #301.

2023-08-27 16:27 UTC, jsolbrig commented
@mindyls This is ready for review. It passes `full_test.sh`.

There are two commented code sections that I would like to leave in place. They will be used in #301 and #303.

2023-08-29 13:09 UTC, mindyls requested changes
I appear to be getting a validation error on this branch: 

```
        try:
            validator = self.validators[validator_id]
        except KeyError as err:
>           raise ValidationError(
                f"No validator found for '{validator_id}'"
                f"\nfrom plugin '{plugin['name']}'"
                f"\nin interface '{plugin['interface']}'"
            ) from err
E           jsonschema.exceptions.ValidationError: No validator found for 'sectors.area_definition_static'
E           from plugin 'CONUS'
E           in interface 'sectors'

geoips/interfaces/base.py:188: ValidationError
======================================================================= short test summary info =======================================================================
FAILED tests/test_pytest/test_plugin_schema/test_yaml_schema.py::test_is_plugin_valid[sectors.area_definition_static-plugin28] - jsonschema.exceptions.ValidationError: No validator found for 'sectors.area_definition_static'
=================================================================== 1 failed, 1317 passed in 29.85s ===================================================================
```

2023-08-29 14:53 UTC, jsolbrig commented on geoips/schema/sectors/static.yaml
> +    pattern: "^((area_definition)|(center))_((static)|(pyrocb)|(atmosriver)|(stitched)|(tc)|(volcano))$"
Yeah, I was noticing that we had something like six schema already and, when I went to add `center_` I was going to need to add six more! It was only going to keep growing.

2023-08-29 14:54 UTC, mindyls approved these changes
pytest error is fixed now.

I think I am ok merging with the schema as is (https://github.com/NRLMMD-GEOIPS/geoips/pull/279#discussion_r1307435833), and we can reassess at a later date.

2023-08-29 14:55 UTC, jsolbrig commented on geoips/interfaces/base.py
> +    @classmethod
Right, nothing changed. Making it a classmethod, though, made it possible to create things like `SectorPluginBase` without circular imports.

2023-08-29 15:02 UTC, christopher-selman approved these changes

2023-08-29 15:14 UTC, mindyls commented on geoips/schema/sectors/static.yaml
> +    pattern: "^((area_definition)|(center))_((static)|(pyrocb)|(atmosriver)|(stitched)|(tc)|(volcano))$"
https://github.com/NRLMMD-GEOIPS/geoips/issues/305

Created that issue. Let's not address this now.  We'll just merge this for now.

2023-08-29 15:19 UTC, mindyls requested changes
Add release notes please.  I'd like to see your summary of these changes...

sectors/static/*.yaml is fine for the YAML updates (don't have to note every single file)

2023-08-29 16:58 UTC, mindyls approved these changes
Release notes added, tests pass.

2023-08-29 16:59 UTC, merged