Clean up optional dependencies throughout GeoIPS Code
NRLMMD-GEOIPS/geoips pull request #438
Opened 2024-02-12 20:46 UTC by evrose54

# Reviewer Checklist

* [x] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [x] NO REQUIRED ***unit tests*** (explain why not required)
* [x] NO REQUIRED ***integration tests*** (explain why not required)
* [x] Required ***documentation*** added for new/modified functionality
* [x] Required ***release notes*** added for new/modified functionality
* [x] Required ***updates to other repos*** complete
       - Data_fusion / geoips_clavrx need updates, see PR's shown below for those changes.

# Related Issues
fixes #338 
This data_fusion [PR](https://github.com/NRLMMD-GEOIPS/data_fusion/pull/30) fixes optional dependencies for that repo.
This geoips_clavrx [PR](https://github.com/NRLMMD-GEOIPS/geoips_clavrx/pull/34) fixes optional dependencies for that repo.

# Testing Instructions
You can run geoips/tests/integration_tests/full_test.sh for testing this PR. Tried it on my side and got a 0 on return. Tests pass.

# Summary
*From GEOIPS#338: 2023-07-19, Clean up optional dependencies*

Some GeoIPS readers include optional dependency statements that are required to read
certain file formats. While keeping these imports as optional is ok, we should clean up
the manner in which this is implemented. To do so, we've created a separate
``geoips.testing.context_manager.py`` script which can handle optional imports scattered
throughout the GeoIPS codebase. This is essentially replacing our old manner of optional
dependencies with a new method that keeps things clean.

    - modified: geoips/plugins/modules/procflows/config_based.py
    - modified: geoips/plugins/modules/readers/abi_netcdf.py
    - modified: geoips/plugins/modules/readers/ahi_hsd.py
    - modified: geoips/plugins/modules/readers/ewsg_netcdf.py
    - modified: geoips/plugins/modules/readers/modis_hdf4.py
    - modified: geoips/plugins/modules/readers/seviri_hrit.py
    - modified: geoips/plugins/modules/readers/utils/geostationary_geolocation.py
    - modified: geoips/plugins/modules/readers/viirs_netcdf.py
    - modified: geoips/utilts/memusg.py
    - added: geoips/utils/context_manager.py

2024-02-12 20:47 UTC, evrose54 commented on docs/source/releases/v1_12_0.rst
> +  * Refactor optional imports in readers to use a context manager function
Don't merge until v1.12.0-release has been merged.

2024-02-12 20:47 UTC, evrose54 commented on geoips/plugins/modules/procflows/single_source.py
> +            ] = source_xarray.filename_extra_fields[field]
black formatting changes.

2024-02-12 20:47 UTC, evrose54 commented on geoips/plugins/modules/procflows/single_source.py
> +                ] = area_def.sector_info["adjustment_id"]
black formatting changes.

2024-02-12 20:48 UTC, evrose54 commented on geoips/plugins/modules/readers/viirs_netcdf.py
> +                        ] = ncvar.getncattr(attrname)
black formatting changes.

2024-02-12 20:48 UTC, evrose54 commented on geoips/xarray_utils/data.py
> +        ] = area_def  # add name of this sector to sector attribute
black formatting changes.

2024-02-20 18:48 UTC, jsolbrig commented on geoips/testing/context_manager.py
I think this should be moved into `geoips/utils/context_managers.py` rather than creating a new `geoips/testing/` directory. That module can be where we put all context managers for GeoIPS (maybe we'll have more in the future).

2024-02-20 19:52 UTC, jsolbrig commented on geoips/testing/context_manager.py
> +def import_optional_dependences(importer):
`dependences` is misspelled and should be `dependencies`. Can you please update this everywhere?

2024-02-20 20:12 UTC, jsolbrig commented on geoips/testing/context_manager.py
I played with this a little. I didn't like how what I'd written previously worked. The fact that it required the filename to be passed was annoying. What do you think of this?

```
@contextmanager
def import_optional_dependences(loglevel="info"):
    """Attempt to import a package and log the event if the import fails.

    Parameters
    ----------
    loglevel : str
        Name of the log level to write to. May be any valid log level (e.g. debug, info,
        etc.).
    """
    try:
        yield None
    except ImportError as err:
        filename = sys.exc_info()[2].tb_frame.f_code.co_filename
        lineno = sys.exc_info()[2].tb_frame.f_lineno
        err_str = f"Failed to import {err.name} at {filename}:{lineno}. "
        err_str += "If you need it, install it."

        getattr(LOG, loglevel)(err_str
```

It would allow updating all of the calls to just be `with import_optional_dependencies()` unless we want a particular call to be at a different level than `info`.

If called like this:
```
with import_optional_dependencies(loglevel="debug"):
    import blahblah
```
the output would look like this:
```
DEBUG:__main__:Failed to import blahblah at /local/home/jsolbrig/geoips/github/geoips/test_import_cm.py:17. If you need it, install it.
```

If `"exception"` is given as the log level, the output would look like this:
```
RROR:__main__:Failed to import blahblah at /local/home/jsolbrig/geoips/github/geoips/test_import_cm.py:17. If you need it, install it.
Traceback (most recent call last):
  File "/local/home/jsolbrig/geoips/github/geoips/test_import_cm.py", line 14, in import_optional_dependences
    yield None
  File "/local/home/jsolbrig/geoips/github/geoips/test_import_cm.py", line 30, in <module>
    import blahblah
ModuleNotFoundError: No module named 'blahblah'
```

2024-04-15 17:02 UTC, jsolbrig requested changes
This PR looks largely ready to go but there appear to still be two instances of the old import style.

- geoips/utils/memusg.py
- geoips/plugins/modules/readers/viirs_netcdf.py

The first looks like it should be fixed. The second is more questionable.

2024-04-15 18:16 UTC, jsolbrig approved these changes

2024-04-15 18:39 UTC, mindyls commented on geoips/plugins/modules/readers/seviri_hrit.py
> +    LOG.info(err_str)
Just FYI, you *can* do 
LOG.info("Failed ne.set_num_threads in seviri_hrit.py"
               "If you need numexpr, install it."
               )

Just break the string up onto 2 lines (no + or anything in between lines).  Just resolve this, it is just for reference.

2024-04-15 18:46 UTC, mindyls approved these changes
I ran amsr2 config based test with only geoips installed, and it completed successfully.

Did not run additional tests, but this looks good to me

2024-04-15 18:51 UTC, merged