398 expand documentation for extending geoips with plugins
NRLMMD-GEOIPS/geoips pull request #491
Opened 2024-04-12 17:14 UTC by evrose54

# Reviewer Checklist

* [ ] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [ ] NO REQUIRED ***unit tests*** (explain why not required)
* [ ] NO REQUIRED ***integration tests*** (explain why not required)
* [ ] Required ***documentation*** added for new/modified functionality
* [ ] Required ***release notes*** added for new/modified functionality
* [ ] NO REQUIRED ***updates to other repos*** (explain why not required)

# Related Issues
fixes NRLMMD-GEOIPS/geoips#398

# Testing Instructions
Run ``./docs/build_docs.sh . geoips html_only``, download the ``build/sphinx/html`` directory and place the ``index.html`` file in your browser to view the new documentation.

# Summary
Will be updated once this PR is ready for review.

2024-04-12 17:17 UTC, evrose54 commented
Still in progress but I wanted to put this up here in case any of you had thoughts on this. Also, I think my main is out of date, which is why some files (like output checkers and single_source) have updates that I did not make. I've tried ``git fetch`` and ``git pull`` on main and that isn't fixing it currently.

2024-12-05 22:03 UTC, biosafetylvl5 commented
Let's get this updated and merged after #830 is merged; it might be easier to start a new branch and copy the content over rather than navigate the merge conflicts

2024-12-17 22:23 UTC, biosafetylvl5 requested changes
I left a few small comments on a few duplicate lines (?). Some of the writing could be copy-edited, but it's very readable as-is. Mostly this is going to need to be refactored a lot to integrate with the new docs.

2024-12-17 22:23 UTC, biosafetylvl5 commented on geoips/plugins/modules/output_checkers/netcdf.py
> +        log_with_emphasis(LOG.interactive, *[line for line in str(resp).split("\n")])
This looks like a duplicate line was added?

2024-12-17 22:23 UTC, biosafetylvl5 commented on geoips/plugins/modules/output_checkers/netcdf.py
> +from geoips.commandline.log_setup import log_with_emphasis
This looks like a duplicate line was added?

2024-12-17 22:23 UTC, biosafetylvl5 commented on pyproject.toml
> +name = "geoips"                                          # geoips package available at the root of the project
Did you use an automated tool to do this?

2025-01-31 18:45 UTC, evrose54 commented
Copy new documentation into a different branch and get that merged into new docs.

2025-05-14 21:35 UTC, biosafetylvl5 commented
Closed in favour of https://github.com/NRLMMD-GEOIPS/geoips/pull/993

2025-05-14 21:35 UTC, closed without merging