Linter, formatter, & Security Analyzer docuemntation
NRLMMD-GEOIPS/geoips pull request #667
Opened 2024-07-15 08:47 UTC by SRIKANTH-KUMAR

# Reviewer Checklist

PR author: Please ensure you meet all of the below requirements, and check boxes appropriately.

Reviewers: Please confirm all required testing/documentation has been completed prior to approving.

**Remove lines that are not applicable, explain if you select "NO REQUIRED"**

* [ ] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [ ] NO REQUIRED ***existing tests*** (explain why not required)
* [ ] Required ***unit tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***unit tests*** (explain why not required)
* [ ] Required ***integration tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***integration tests*** (explain why not required)
* [ ] Required ***documentation*** added for new/modified functionality
* [ ] NO REQUIRED ***documentation*** (explain why not required)
* [ ] Required ***release notes*** added for new/modified functionality
* [ ] NO REQUIRED ***release notes*** (explain why not required)
* [ ] Required ***updates to other repos*** complete
* [ ] NO REQUIRED ***updates to other repos*** (explain why not required)

https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#NNN

# Testing Instructions

# Summary

# Output

2024-07-23 22:51 UTC, biosafetylvl5 requested changes
I copy-edited your writing for clarity and brevity. Please keep these maxims in mind when writing:

  - Quantity: Offer just the right amount of information; no more or less than is required for the current purpose
  - Relation (Relevance): Write only relevant things
  - Manner: Be clear, orderly, brief, unambiguous

Please make these changes:

 - Add the other linters + formatters we use
 - Make sure you are passing doc8 and other CI checks
 - Include Visual Studio Environmental setup
 - Add a release note

Thank you for your work on this @Srikant-Kumar-Gampa @SRIKANTH-KUMAR ! Please let me know if you have any questions or need assistance.

2024-10-09 18:33 UTC, biosafetylvl5 commented
Fixes #484

2024-10-09 18:34 UTC, biosafetylvl5 commented
Fixes #501

2025-04-17 23:05 UTC, srikanth-kumar commented
@jsolbrig, @biosafetylvl5 and @srikanth-kumar discussed the issue and agreed that @biosafetylvl5 will take it over.

2025-04-22 21:41 UTC, closed without merging