Automate ``create_plugin_registries``
NRLMMD-GEOIPS/geoips pull request #781
Opened 2024-09-16 20:41 UTC by evrose54

# Reviewer Checklist

* [ ] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [ ] Required ***unit tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***integration tests*** (explain why not required)
* [ ] Required ***documentation*** added for new/modified functionality
* [ ] Required ***release notes*** added for new/modified functionality
* [ ] NO REQUIRED ***updates to other repos*** (explain why not required)

# Related Issues
fixes NRLMMD-GEOIPS/geoips#647

# Testing Instructions
Run ``./tests/integration_tests/full_test.sh``

# Summary
Will fill out once PR is ready for review.

# Output

```python
from geoips.interfaces import readers

test_plg = readers.get_plugin("fake_plugin")

# OUTPUT

Running create_plugin_registries due to a missing plugin.
16_203926 create_plugin_registries.py:318  INTERACTIVE: Writing /local/home/evan/geoips/geoips_packages/geoips_clavrx/geoips_clavrx/registered_plugins.json
16_203927 create_plugin_registries.py:318  INTERACTIVE: Writing /local/home/evan/geoips/geoips_packages/data_fusion/data_fusion/registered_plugins.json
16_203927 create_plugin_registries.py:318  INTERACTIVE: Writing /local/home/evan/geoips/geoips_packages/recenter_tc/recenter_tc/registered_plugins.json
16_203927 create_plugin_registries.py:318  INTERACTIVE: Writing /local/home/evan/geoips/geoips_packages/geoips_plugin_example/geoips_plugin_example/registered_plugins.json
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'interp_scipy' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'boxdefinitions' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'interp_pyresample' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'geostationary_geolocation' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'hrit_reader' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'remss_reader' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:820  INTERACTIVE: Skipping module 'tc_file_naming' from 'geoips', interface_name is 'None'
16_203928 create_plugin_registries.py:318  INTERACTIVE: Writing /local/home/evan/geoips/geoips_packages/geoips/geoips/registered_plugins.json

PluginError: Plugin 'fake_plugin', from interface 'readers' appears to not exist.
Create plugin, then call create_plugin_registries?
```

2024-10-22 22:34 UTC, jsolbrig requested changes
This should have a CLI flag added to allow turning on automatic registry creation.

2025-01-14 18:12 UTC, evrose54 commented
Add ``GEOIPS_REBUILD_REGISTRIES`` to base_paths.py and have this default to false. If set to True, set ``rebulid_registries`` to True for all ``get_plugin`` calls.

2025-02-03 21:52 UTC, jsolbrig commented
> have this default to false.

Let's have this default to `True` instead, as discussed with NRL last week.

2025-02-03 23:14 UTC, evrose54 commented
I have this defaulting to True now, running full test to see if things are working.

2025-02-03 23:52 UTC, jsolbrig commented on geoips/commandline/args.py
> +            default=getenv("GEOIPS_REBUILD_REGISTRIES", False),
Should this also be `True` rather than `False`?

2025-02-04 00:25 UTC, evrose54 commented on geoips/commandline/args.py
> +            default=getenv("GEOIPS_REBUILD_REGISTRIES", False),
Good catch! I updated this. Thanks Jeremy.

2025-02-04 00:27 UTC, jsolbrig approved these changes

2025-02-06 22:42 UTC, mindyls commented on geoips/interfaces/base.py
> +        rebuild_registries: boolean (default=False)
This does not actually have a default at this point.

2025-02-06 22:43 UTC, mindyls commented on geoips/interfaces/base.py
> +class BaseInterface(abc.ABC):
This just allows using the abc.abstractmethod ?

2025-02-06 22:49 UTC, mindyls commented on geoips/interfaces/base.py
> +                    self.plugin_registry.registered_plugins["module_based"]
When would it hit this location of calling create_plugin_registries rather than through get_plugin / retry_get_plugin?

2025-02-06 22:58 UTC, mindyls commented on geoips/interfaces/base.py
> +        rebuild_registries: boolean (default=False)
I like having the methods themselves default to False, and the overall environment variable default to True, FWIW.

2025-02-06 22:58 UTC, mindyls approved these changes
Just a few comments to review

2025-02-10 16:57 UTC, evrose54 commented on geoips/interfaces/base.py
> +                    self.plugin_registry.registered_plugins["module_based"]
Could you expand on this a bit? I'm a bit confused by your question. When I wrote this code, I envisioned this ``except`` statement to be hit if the plugin registry itself didn't exist. The commandline uses the plugin registry, and this could also be hit when ``get_plugin`` is ran as well.

2025-02-10 18:13 UTC, jsolbrig commented on tests/unit_tests/plugins/test_get_plugin.py
> +                    yield (interface_name, plugin_name, "normal")
I don't see anything here that aligns with the comment, restricting the number of plugins to 5.

2025-02-10 18:26 UTC, jsolbrig commented on tests/unit_tests/plugins/test_get_plugin.py
> +    """Yield tuples of (interface_name, plugin_name)."""
Can you please update and improve this docstring so it's easier for someone who is reading this to understand what this is returning and why? It looks like the tuple in the docstring needs another element added and it would be useful to say how the three elements are intended to be used, e.g.:

```
Yield tuples of (interface_name, plugin_name_tuple, expected_outcome) for use in other tests.

Yield tuples to use when attempting to load a plugin in the `test_get_plugin` function. The tuple will contain three elements:

- interface_name: The name of the interface that we want to attempt to load a plugin from.
- plugin_name_tuple: A tuple containing one or two strings defining which plugin should be loaded. Two strings is used for the Products interface and one string is used for all other interfaces.
- expected_output: A string describing the expected outcome. This is used in the `test_get_plugin` function to determine which part of the logic to follow and how to test the results.
```

Note that I'm saying `plugin_name_tuple` because of another comment that would help clean up `test_get_plugin` a bit.

2025-02-10 19:47 UTC, jsolbrig commented on tests/unit_tests/plugins/test_get_plugin.py
> +            assert curr_interface.get_plugin(plugin_name, rebuild_registries=True)
Another option here to cut down on code would be to always make the plugin name a tuple and do this:
```
assert curr_interface.get_plugin(*plugin_name, rebuild_registries=True)
```

2025-02-10 20:05 UTC, jsolbrig commented on tests/unit_tests/plugins/test_get_plugin.py
> +def test_get_plugin(int_plug_tuple):
I think it would be worth also testing with `rebuild_registries=False` to ensure that we get correct behavior there, too.

2025-02-10 20:19 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +            assert curr_interface.get_plugin(plugin_name, rebuild_registries=True)
Only reason I didn't do that initially is that when you unpack a string that isn't a tuple, you get something like this:
```python
In [1]: c = "an_example_string"

In [2]: d = ("a_tuple", "of_strings")

In [3]: print(*c)
a n _ e x a m p l e _ s t r i n g

In [4]: print(*d)
a_tuple of_strings
```
I could however always return a tuple, even if it only has one string, and this would then work.

2025-02-10 20:19 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +def test_get_plugin(int_plug_tuple):
Agreed. I'll add that test now.

2025-02-10 20:20 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +    """Yield tuples of (interface_name, plugin_name)."""
I'll update this docstring. Are you ok if I use what you provided? It does a good job clarifying what this function does.

2025-02-10 20:20 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +                    yield (interface_name, plugin_name, "normal")
Good catch. I added a conditional to make that comment correct.

2025-02-10 20:21 UTC, jsolbrig commented on tests/unit_tests/plugins/test_get_plugin.py
> +            assert curr_interface.get_plugin(plugin_name, rebuild_registries=True)
Yeah, I think that would make this cleaner if `plugin_name` was always a tuple. Much easier to explain in the docstring, too.

2025-02-10 20:38 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +            assert curr_interface.get_plugin(plugin_name, rebuild_registries=True)
Made all of the names tuples so that can be simplified.

2025-02-10 20:38 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +def test_get_plugin(int_plug_tuple):
Done!

2025-02-10 20:38 UTC, evrose54 commented on tests/unit_tests/plugins/test_get_plugin.py
> +    """Yield tuples of (interface_name, plugin_name)."""
Updated using what you posted above.

2025-02-10 21:25 UTC, jsolbrig approved these changes

2025-02-14 23:23 UTC, mindyls commented on geoips/interfaces/base.py
> +                    self.plugin_registry.registered_plugins["module_based"]
I guess when is get module based plugins called?

2025-02-14 23:27 UTC, mindyls approved these changes
Looks good, you can resolve conversations

2025-02-18 17:16 UTC, evrose54 commented on geoips/interfaces/base.py
> +                    self.plugin_registry.registered_plugins["module_based"]
I've got an answer now. This would be hit if no registries existed, or, somehow, no module plugins existed. Same for yaml plugins in the property below. This is nice as we can automatically run ``create_plugin_registries`` the first time an interface is used, if no registries exist. This would likely be hit the first time a user installs GeoIPS but no plugin registries have been created yet.

2025-02-18 18:06 UTC, mindyls approved these changes

2025-02-18 20:28 UTC, jsolbrig commented on docs/source/concepts/functionality/plugin-registries.rst
It looks like there is some leftover stuff from the previous documentation:

```


Note

We hope to automate the process of creating/updating the plugin registries in the future to avoid requiring the user to directly call create_plugin_registries.
```

It would be good to include information about running `create_plugin_registries` manually, but I think this part looks out of date.

2025-02-18 21:37 UTC, evrose54 commented on docs/source/concepts/functionality/plugin-registries.rst
I removed this old comment. Lines 24+ should accomplish how to manually run ``create_plugin_registries``, let me know if you feel otherwise!

2025-02-18 22:02 UTC, jsolbrig approved these changes

2025-02-18 22:04 UTC, jsolbrig commented on docs/source/concepts/functionality/plugin-registries.rst
Thanks @evrose54

2025-02-18 22:05 UTC, merged