Standardize Reader Arguments
NRLMMD-GEOIPS/geoips pull request #816
Opened 2024-11-05 09:55 UTC by srikanth-kumar

# Reviewer Checklist

PR author: Please ensure you meet all of the below requirements, and check boxes appropriately.

Reviewers: Please confirm all required testing/documentation has been completed prior to approving.

**Remove lines that are not applicable, explain if you select "NO REQUIRED"**

* [ ] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [ ] NO REQUIRED ***existing tests*** (explain why not required)
* [ ] Required ***unit tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***unit tests*** (explain why not required)
* [ ] Required ***integration tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***integration tests*** (explain why not required)
* [ ] Required ***documentation*** added for new/modified functionality
* [ ] NO REQUIRED ***documentation*** (explain why not required)
* [ ] Required ***release notes*** added for new/modified functionality
* [ ] NO REQUIRED ***release notes*** (explain why not required)
* [ ] Required ***updates to other repos*** complete
* [ ] NO REQUIRED ***updates to other repos*** (explain why not required)

https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#NNN

# Testing Instructions

# Summary

# Output

2024-12-31 19:01 UTC, jsolbrig requested changes
I left several comments regarding `reader_kwargs` and `bg_reader_kwargs`. I'm unsure whether we should outright remove this functionality. 

@mindyls, can you take a look and see what you think? Keep in mind that this PR results in all of the reader call signatures being identical. I'm not sure whether `reader_kwargs` and `bg_reader_kwargs` still serve a purpose, though. Maybe we sometimes want to pass `area_def` at the command line? Would that be helpful in some way?

If we do decide to remove `reader_kwargs` and `bg_reader_kwargs`, we should ensure that we also remove instances where they are used in the test scripts. For example, in the main GeoIPS repo, the following scripts use one or both of those keywords:

```
./amsr2.config_based_no_compare.sh
./amsr2.tc.89H-Physical.histogram_netcdf.sh
./ami.WV-Upper.unprojected_image.sh
./amsr2.config_based_no_compare_full.sh
./amsr2.tc.89H-Physical.imagery_annotated.sh
```

From what I can tell, no other public package uses these arguments, but they may be used internally.

2025-02-11 17:20 UTC, srikanth-kumar commented on geoips/plugins/modules/readers/abi_l2_netcdf.py
> +def call(fnames, area_def=None, metadata_only=False, chans=None, self_register=False):
Thanks, Jeremy. This is fixed now.

2025-04-10 22:57 UTC, jsolbrig commented on geoips/plugins/modules/procflows/config_based.py
> +        bg_xobjs = bg_reader_plugin(bg_files, metadata_only=True)
This does serve a purpose. Let's keep it for now, please.

2025-04-10 22:57 UTC, jsolbrig commented on geoips/plugins/modules/procflows/config_based.py
> +    xobjs = reader_plugin(fnames, metadata_only=True)
We should definitely keep `reader_kwargs`. In fact, I'm going to suggest that we use it as we deprecate `chans` in favor of `variables`.

2025-04-16 17:53 UTC, srikanth-kumar commented on geoips/plugins/modules/procflows/config_based.py
> +    xobjs = reader_plugin(fnames, metadata_only=True)
I’ve restored `**reader_kwargs`. I wasn’t aware that it is used in the `Satpy` reader — thank you for letting me know, Jeremy.

This is ready to be resolved.

2025-04-16 17:54 UTC, srikanth-kumar commented on geoips/plugins/modules/procflows/single_source.py
> +    xobjs = reader_plugin(fnames, metadata_only=True)
Restored **reader_kwargs

2025-04-16 17:54 UTC, srikanth-kumar commented on geoips/plugins/modules/procflows/single_source.py
> +            chans=variables,
Restored **reader_kwargs

2025-04-16 17:55 UTC, srikanth-kumar commented on geoips/plugins/modules/procflows/config_based.py
> +        bg_xobjs = bg_reader_plugin(bg_files, metadata_only=True)
Restored `**bg_reader_kwargs`.

2025-04-22 19:33 UTC, mindyls commented on geoips/plugins/yaml/sectors/static/abu_dhabi.yaml
> +  city: AbuDhabi
Are we putting region back?

2025-04-22 19:38 UTC, jsolbrig commented on geoips/plugins/yaml/sectors/static/abu_dhabi.yaml
> +  city: AbuDhabi
Nope, this is getting fixed.

2025-05-13 16:50 UTC, christopher-selman approved these changes

2025-05-20 16:58 UTC, biosafetylvl5 commented
Change requested by mindy - add back test arguments

2025-05-20 17:00 UTC, mindyls commented on geoips/plugins/modules/readers/ahi_hsd.py
> -    test_arg="AHI Default Test Arg",
We need to continue to support arbitrary kwargs, this "test_arg" is here to ensure we don't remove support for arbitrary kwargs.  It should still be included in a test script as well

2025-05-20 17:01 UTC, mindyls commented on geoips/plugins/modules/readers/amsr2_netcdf.py
> -    test_arg="AMSR2 Default Test Arg",
This is required.

2025-05-20 20:49 UTC, jsolbrig submitted a review, later dismissed

2025-05-21 23:15 UTC, srikanth-kumar commented on geoips/plugins/modules/readers/ahi_hsd.py
> -    test_arg="AHI Default Test Arg",
restored.

2025-05-21 23:15 UTC, srikanth-kumar commented on geoips/plugins/modules/readers/amsr2_netcdf.py
> -    test_arg="AMSR2 Default Test Arg",
restored

2025-05-22 00:01 UTC, mindyls commented on geoips/plugins/modules/procflows/config_based.py
> +        bg_xobjs = bg_reader_plugin(bg_files, metadata_only=True)
And we need to ensure they get passed all the way through the procflows

2025-05-22 00:03 UTC, mindyls approved these changes

2025-05-22 00:07 UTC, biosafetylvl5 approved these changes

2025-05-22 20:21 UTC, merged